import logging
from fastapi import APIRouter

from app.models.schemas import NewsRequest, SummarizeRequest
from app.services.llm_service import run_agent, summarize_news
from app.services.news_service import fetch_news

logger = logging.getLogger(__name__)
router = APIRouter()

@router.post("/generate-news")
async def generate_news(data: NewsRequest):
    try:
        result = run_agent(topic=data.topic)
        return {"success": True, "news": result}
    except Exception as e:
        logger.error("generate-news error: %s", e)
        return {"success": False, "error": str(e)}

@router.post("/summarize-news")
async def summarize_news_endpoint(data: SummarizeRequest):
    """
    Fetches fresh articles for the requested topic and returns a
    broadcast-style summary generated by the xAI Grok LLM.
    """
    try:
        news_data = fetch_news(
            query=data.topic,
            limit=data.limit,
            time_published=data.time_published,
        )

        articles = []
        if news_data and "data" in news_data:
            articles = news_data["data"]

        summary = summarize_news(topic=data.topic, articles=articles)

        return {
            "success": True,
            "topic": data.topic,
            "article_count": len(articles),
            "summary": summary,
        }

    except Exception as e:
        logger.error("summarize-news error: %s", e)
        return {"success": False, "error": str(e)}
